apiVersion: v1
kind: Namespace
metadata:
  name: crda
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crda-backend
  namespace: crda
  labels:
    app: crda-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crda-backend
  template:
    metadata:
      labels:
        app: crda-backend
    spec:
      containers:
      - name: crda-backend
        image: quay.io/ecosystem-appeng/crda-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: API_SNYK_TOKEN
          valueFrom:
            secretKeyRef:
              name: crda-secret
              key: api-snyk-token
        - name: API_TIDELIFT_TOKEN
          valueFrom:
            secretKeyRef:
              name: crda-secret
              key: api-tidelift-token
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: crda-backend
  name: crda-backend
  namespace: crda
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: crda-backend
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: crda-backend
  name: crda-backend
  namespace: crda
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: crda-backend