{
 "title": "Exhort",
 "description": "Trusted Content Exhort service",
 "tags": [
  "exhort",
  "trusted-content"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "% Success (by interval)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status!~\"[4-5].*\", namespace=\"exhort-stage\", job=\"exhort\"}[2m])) / \n(sum(rate(http_server_requests_seconds_count{namespace=\"exhort-stage\", job=\"exhort\"}[2m])) - \n(sum(rate(http_server_requests_seconds_count{status=~\"404|499\", namespace=\"exhort-stage\", job=\"exhort\"}[2m])) or vector(0)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS (Total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"exhort-stage\", job=\"exhort\"}[2m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "RPS (by endpoint)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"exhort-stage\", job=\"exhort\"}[2m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"exhort-stage\", job=\"exhort\", status!~\"5..\"}[7d]))\n/\nsum(rate(http_server_requests_seconds_count{namespace=~\"exhort-stage\", job=\"exhort\"}[7d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (NOT READY)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"exhort-stage\", job=\"exhort\", status!~\"5..\"}[7d]))\n/\nsum(rate(http_server_requests_seconds_count{namespace=~\"exhort-stage\", job=\"exhort\"}[7d]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}