apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RHEcosystemAppEng/exhort?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[push]'
    pipelinesascode.tekton.dev/on-target-branch: '[main]'
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: exhort
    appstudio.openshift.io/component: exhort
    pipelines.appstudio.openshift.io/type: build
  name: exhort-on-push
  namespace: trusted-content-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/trusted-content-tenant/exhort/exhort:{{revision}}
  - name: dockerfile
    value: src/main/docker/Dockerfile.jvm.staged
  - name: path-context
    value: .
  - name: build-args-file
    value: ../../../entitlement/gh-creds.txt
  - name: entitlement-secret
    value: gh-credentials
  taskRunSpecs:
    - pipelineTaskName: build-container
      stepSpecs:
        - name: build
          computeResources:
            requests:
              memory: 8Gi
            limits:
              memory: 8Gi
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/trustification/dependency-analytics-pipelines
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/default-build.yaml
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
  - name: mvn-settings
    secret:
      secretName: exhort-mvn-settings
