---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: openjdk-redis-6gb
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: image-build
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    OpenJDK 21 task with a Redis sidecar. The task requests 4Gi of memory with a limit of 6Gi
  params:
  - name: JDK_IMAGE
    description: Reference of the image buildah will produce.
    default: registry.redhat.io/ubi9/openjdk-21:1.18
  - name: REDIS_IMAGE
    description: The location of the buildah builder image.
    default: docker.io/redis/redis-stack:7.2.0-v7
  - name: SCRIPT
    description: The script to execute in the jdk image
    default: |
      mvn -B verify
  workspaces:
  - name: source
  steps:
  - name: run-tests
    image: $(params.JDK_IMAGE)
    workingDir: $(workspaces.source.path)/source
    script: |
      $(params.SCRIPT)
    computeResources:
      requests:
        memory: 4Gi
      limits:
        memory: 6Gi
    workspaces:
      - name: source
        workspace: workspace
  sidecars:
    - image: $(params.REDIS_IMAGE)
      name: redis-stack